// Centralized season configuration — update here when seasons change
export const LEAGUE_SEASONS: Record<string, { label: string; seasonId: string; league: string; country: string }> = {
  premier_league: {
    label: "Premier League",
    seasonId: "sr:season:118689",
    league: "Premier League",
    country: "England",
  },
  la_liga: {
    label: "La Liga",
    seasonId: "sr:season:118691",
    league: "La Liga",
    country: "Spain",
  },
  serie_a: {
    label: "Serie A",
    seasonId: "sr:season:118699",
    league: "Serie A",
    country: "Italy",
  },
  bundesliga: {
    label: "Bundesliga",
    seasonId: "sr:season:118697",
    league: "Bundesliga",
    country: "Germany",
  },
  ligue_1: {
    label: "Ligue 1",
    seasonId: "sr:season:118693",
    league: "Ligue 1",
    country: "France",
  },
};

// Sportradar competition ID → season key mapping
export const COMPETITION_TO_SEASON: Record<string, string> = {
  "sr:competition:17": "premier_league",
  "sr:competition:8": "la_liga",
  "sr:competition:23": "serie_a",
  "sr:competition:35": "bundesliga",
  "sr:competition:34": "ligue_1",
};

// Team name aliases for fuzzy matching (Sportradar name → canonical DB name)
export const TEAM_NAME_ALIASES: Record<string, string> = {
  // England
  "internazionale": "inter milan",
  "inter milano": "inter milan",
  "fc internazionale milano": "inter milan",
  "atletico de madrid": "atletico madrid",
  "atlético de madrid": "atletico madrid",
  "atlético madrid": "atletico madrid",
  "club atlético de madrid": "atletico madrid",
  "wolverhampton wanderers": "wolves",
  "wolverhampton": "wolves",
  "tottenham hotspur": "tottenham",
  "west ham united": "west ham",
  "manchester city fc": "manchester city",
  "manchester united fc": "manchester united",
  "arsenal fc": "arsenal",
  "chelsea fc": "chelsea",
  "liverpool fc": "liverpool",
  "newcastle united fc": "newcastle",
  "newcastle united": "newcastle",
  "aston villa fc": "aston villa",
  "nottingham forest fc": "nottingham forest",
  "brighton and hove albion": "brighton",
  "brighton & hove albion": "brighton",
  "leicester city fc": "leicester city",
  "leicester city": "leicester",
  "crystal palace fc": "crystal palace",
  "everton fc": "everton",
  "fulham fc": "fulham",
  "bournemouth": "afc bournemouth",
  "afc bournemouth": "bournemouth",
  "ipswich town fc": "ipswich town",
  "ipswich town": "ipswich",
  "southampton fc": "southampton",
  "brentford fc": "brentford",
  // Spain
  "real madrid cf": "real madrid",
  "fc barcelona": "barcelona",
  "rcd espanyol": "espanyol",
  "real sociedad de fútbol": "real sociedad",
  "real betis balompié": "real betis",
  "real betis": "betis",
  "villarreal cf": "villarreal",
  "sevilla fc": "sevilla",
  "valencia cf": "valencia",
  "ca osasuna": "osasuna",
  "rcd mallorca": "mallorca",
  "celta de vigo": "celta vigo",
  "rc celta de vigo": "celta vigo",
  "getafe cf": "getafe",
  "deportivo alavés": "alaves",
  "deportivo alaves": "alaves",
  "ud las palmas": "las palmas",
  "real valladolid": "valladolid",
  "cd leganés": "leganes",
  "cd leganes": "leganes",
  "girona fc": "girona",
  "athletic club": "athletic bilbao",
  "athletic de bilbao": "athletic bilbao",
  // Italy
  "juventus fc": "juventus",
  "ac milan": "milan",
  "ssc napoli": "napoli",
  "as roma": "roma",
  "ss lazio": "lazio",
  "acf fiorentina": "fiorentina",
  "atalanta bc": "atalanta",
  "torino fc": "torino",
  "bologna fc 1909": "bologna",
  "bologna fc": "bologna",
  "us lecce": "lecce",
  "cagliari calcio": "cagliari",
  "parma calcio 1913": "parma",
  "hellas verona fc": "verona",
  "hellas verona": "verona",
  "genoa cfc": "genoa",
  "udinese calcio": "udinese",
  "empoli fc": "empoli",
  "us sassuolo calcio": "sassuolo",
  "como 1907": "como",
  "venezia fc": "venezia",
  "ac monza": "monza",
  // Germany
  "fc bayern münchen": "bayern munich",
  "fc bayern munich": "bayern munich",
  "bayern münchen": "bayern munich",
  "borussia dortmund": "dortmund",
  "bvb borussia dortmund": "dortmund",
  "bayer 04 leverkusen": "bayer leverkusen",
  "bayer leverkusen": "leverkusen",
  "rb leipzig": "leipzig",
  "rasenballsport leipzig": "leipzig",
  "vfb stuttgart": "stuttgart",
  "eintracht frankfurt": "frankfurt",
  "sg eintracht frankfurt": "frankfurt",
  "borussia mönchengladbach": "monchengladbach",
  "borussia monchengladbach": "monchengladbach",
  "vfl wolfsburg": "wolfsburg",
  "sc freiburg": "freiburg",
  "sport-club freiburg": "freiburg",
  "1. fc union berlin": "union berlin",
  "fc union berlin": "union berlin",
  "tsg 1899 hoffenheim": "hoffenheim",
  "tsg hoffenheim": "hoffenheim",
  "1. fsv mainz 05": "mainz",
  "fsv mainz 05": "mainz",
  "fc augsburg": "augsburg",
  "1. fc heidenheim 1846": "heidenheim",
  "fc heidenheim": "heidenheim",
  "sv werder bremen": "werder bremen",
  "werder bremen": "bremen",
  "vfl bochum 1848": "bochum",
  "vfl bochum": "bochum",
  "fc st. pauli": "st. pauli",
  "holstein kiel": "kiel",
  // France
  "paris saint-germain": "psg",
  "paris saint-germain fc": "psg",
  "olympique de marseille": "marseille",
  "olympique marseille": "marseille",
  "as monaco": "monaco",
  "as monaco fc": "monaco",
  "olympique lyonnais": "lyon",
  "olympique lyon": "lyon",
  "losc lille": "lille",
  "losc lille métropole": "lille",
  "stade rennais fc": "rennes",
  "stade rennais": "rennes",
  "rc lens": "lens",
  "racing club de lens": "lens",
  "ogc nice": "nice",
  "olympique gymnaste club nice": "nice",
  "rc strasbourg alsace": "strasbourg",
  "rc strasbourg": "strasbourg",
  "fc nantes": "nantes",
  "stade brestois 29": "brest",
  "stade brest": "brest",
  "toulouse fc": "toulouse",
  "montpellier hsc": "montpellier",
  "montpellier hérault sc": "montpellier",
  "le havre ac": "le havre",
  "afc le havre": "le havre",
  "stade de reims": "reims",
  "as saint-étienne": "saint-etienne",
  "as saint-etienne": "saint-etienne",
  "angers sco": "angers",
  "aj auxerre": "auxerre",
};

// Resolve a team name to its canonical form
export function resolveTeamName(name: string): string {
  const lower = name.toLowerCase().trim();
  return TEAM_NAME_ALIASES[lower] ?? lower;
}
