// Centralized season configuration — update here when seasons change
export const LEAGUE_SEASONS: Record<string, { label: string; seasonId: string; league: string; country: string }> = {
  premier_league: {
    label: "Premier League",
    seasonId: "sr:season:130281",
    league: "Premier League",
    country: "England",
  },
  la_liga: {
    label: "La Liga",
    seasonId: "sr:season:130805",
    league: "La Liga",
    country: "Spain",
  },
  serie_a: {
    label: "Serie A",
    seasonId: "sr:season:130971",
    league: "Serie A",
    country: "Italy",
  },
  bundesliga: {
    label: "Bundesliga",
    seasonId: "sr:season:130571",
    league: "Bundesliga",
    country: "Germany",
  },
  ligue_1: {
    label: "Ligue 1",
    seasonId: "sr:season:131609",
    league: "Ligue 1",
    country: "France",
  },
  wc_qualifiers_europe: {
    label: "WC Qualifiers Europe",
    seasonId: "sr:season:127075",
    league: "WC Qualifiers Europe",
    country: "World",
  },
  wc_qualifiers_conmebol: {
    label: "WC Qualifiers CONMEBOL",
    seasonId: "sr:season:109025",
    league: "WC Qualifiers CONMEBOL",
    country: "World",
  },
  wc_qualifiers_concacaf: {
    label: "WC Qualifiers CONCACAF",
    seasonId: "sr:season:115355",
    league: "WC Qualifiers CONCACAF",
    country: "World",
  },
  world_cup_2026: {
    label: "World Cup 2026",
    seasonId: "sr:season:101177",
    league: "World Cup 2026",
    country: "World",
  },
  champions_league: {
    label: "Champions League",
    seasonId: "sr:season:131071",
    league: "Champions League",
    country: "Europe",
  },
  europa_league: {
    label: "Europa League",
    seasonId: "sr:season:131073",
    league: "Europa League",
    country: "Europe",
  },
  eredivisie: {
    label: "Eredivisie",
    seasonId: "sr:season:130587",
    league: "Eredivisie",
    country: "Netherlands",
  },
  primeira_liga: { label: "Primeira Liga", seasonId: "", league: "Primeira Liga", country: "Portugal" },
  jupiler_pro_league: { label: "Jupiler Pro League", seasonId: "", league: "Jupiler Pro League", country: "Belgium" },
  super_lig: { label: "Süper Lig", seasonId: "", league: "Süper Lig", country: "Turkey" },
  scottish_premiership: { label: "Premiership", seasonId: "", league: "Premiership", country: "Scotland" },
  swiss_super_league: { label: "Super League", seasonId: "", league: "Super League", country: "Switzerland" },
  austrian_bundesliga: { label: "Bundesliga Austria", seasonId: "", league: "Bundesliga Austria", country: "Austria" },
  greek_super_league: { label: "Super League 1", seasonId: "", league: "Super League 1", country: "Greece" },
  danish_superliga: { label: "Superliga", seasonId: "", league: "Superliga", country: "Denmark" },
  allsvenskan: { label: "Allsvenskan", seasonId: "", league: "Allsvenskan", country: "Sweden" },
  eliteserien: { label: "Eliteserien", seasonId: "", league: "Eliteserien", country: "Norway" },
  ekstraklasa: { label: "Ekstraklasa", seasonId: "", league: "Ekstraklasa", country: "Poland" },
  chance_liga: { label: "Chance Liga", seasonId: "", league: "Chance Liga", country: "Czech Republic" },
  hnl: { label: "HNL", seasonId: "", league: "HNL", country: "Croatia" },
  ukraine_premier_league: { label: "Premier League Ukraine", seasonId: "", league: "Premier League Ukraine", country: "Ukraine" },
};

// Sportradar competition ID → season key mapping
export const COMPETITION_TO_SEASON: Record<string, string> = {
  "sr:competition:17": "premier_league",
  "sr:competition:8": "la_liga",
  "sr:competition:23": "serie_a",
  "sr:competition:35": "bundesliga",
  "sr:competition:34": "ligue_1",
  "sr:competition:7": "champions_league",
  "sr:competition:679": "europa_league",
  "sr:competition:37": "eredivisie",
};

// Team name aliases for fuzzy matching (Sportradar name → canonical DB name)
export const TEAM_NAME_ALIASES: Record<string, string> = {
  // England
  "internazionale": "inter milan",
  "inter milano": "inter milan",
  "fc internazionale milano": "inter milan",
  "atletico de madrid": "atletico madrid",
  "atlético de madrid": "atletico madrid",
  "atlético madrid": "atletico madrid",
  "club atlético de madrid": "atletico madrid",
  "wolverhampton wanderers": "wolves",
  "wolverhampton": "wolves",
  "tottenham hotspur": "tottenham",
  "west ham united": "west ham",
  "manchester city fc": "manchester city",
  "manchester united fc": "manchester united",
  "arsenal fc": "arsenal",
  "chelsea fc": "chelsea",
  "liverpool fc": "liverpool",
  "newcastle united fc": "newcastle",
  "newcastle united": "newcastle",
  "aston villa fc": "aston villa",
  "nottingham forest fc": "nottingham forest",
  "brighton and hove albion": "brighton",
  "brighton & hove albion": "brighton",
  "leicester city fc": "leicester city",
  "leicester city": "leicester",
  "crystal palace fc": "crystal palace",
  "everton fc": "everton",
  "fulham fc": "fulham",
  "bournemouth": "afc bournemouth",
  "afc bournemouth": "bournemouth",
  "ipswich town fc": "ipswich town",
  "ipswich town": "ipswich",
  "southampton fc": "southampton",
  "brentford fc": "brentford",
  // Spain
  "real madrid cf": "real madrid",
  "fc barcelona": "barcelona",
  "rcd espanyol": "espanyol",
  "real sociedad de fútbol": "real sociedad",
  "real betis balompié": "real betis",
  "real betis": "betis",
  "villarreal cf": "villarreal",
  "sevilla fc": "sevilla",
  "valencia cf": "valencia",
  "ca osasuna": "osasuna",
  "rcd mallorca": "mallorca",
  "celta de vigo": "celta vigo",
  "rc celta de vigo": "celta vigo",
  "getafe cf": "getafe",
  "deportivo alavés": "alaves",
  "deportivo alaves": "alaves",
  "ud las palmas": "las palmas",
  "real valladolid": "valladolid",
  "cd leganés": "leganes",
  "cd leganes": "leganes",
  "girona fc": "girona",
  "athletic club": "athletic bilbao",
  "athletic de bilbao": "athletic bilbao",
  // Italy
  "juventus fc": "juventus",
  "ac milan": "milan",
  "ssc napoli": "napoli",
  "as roma": "roma",
  "ss lazio": "lazio",
  "acf fiorentina": "fiorentina",
  "atalanta bc": "atalanta",
  "torino fc": "torino",
  "bologna fc 1909": "bologna",
  "bologna fc": "bologna",
  "us lecce": "lecce",
  "cagliari calcio": "cagliari",
  "parma calcio 1913": "parma",
  "hellas verona fc": "verona",
  "hellas verona": "verona",
  "genoa cfc": "genoa",
  "udinese calcio": "udinese",
  "empoli fc": "empoli",
  "us sassuolo calcio": "sassuolo",
  "como 1907": "como",
  "venezia fc": "venezia",
  "ac monza": "monza",
  // Germany
  "fc bayern münchen": "bayern munich",
  "fc bayern munich": "bayern munich",
  "bayern münchen": "bayern munich",
  "borussia dortmund": "dortmund",
  "bvb borussia dortmund": "dortmund",
  "bayer 04 leverkusen": "bayer leverkusen",
  "bayer leverkusen": "leverkusen",
  "rb leipzig": "leipzig",
  "rasenballsport leipzig": "leipzig",
  "vfb stuttgart": "stuttgart",
  "eintracht frankfurt": "frankfurt",
  "sg eintracht frankfurt": "frankfurt",
  "borussia mönchengladbach": "monchengladbach",
  "borussia monchengladbach": "monchengladbach",
  "vfl wolfsburg": "wolfsburg",
  "sc freiburg": "freiburg",
  "sport-club freiburg": "freiburg",
  "1. fc union berlin": "union berlin",
  "fc union berlin": "union berlin",
  "tsg 1899 hoffenheim": "hoffenheim",
  "tsg hoffenheim": "hoffenheim",
  "1. fsv mainz 05": "mainz",
  "fsv mainz 05": "mainz",
  "fc augsburg": "augsburg",
  "1. fc heidenheim 1846": "heidenheim",
  "fc heidenheim": "heidenheim",
  "sv werder bremen": "werder bremen",
  "werder bremen": "bremen",
  "vfl bochum 1848": "bochum",
  "vfl bochum": "bochum",
  "fc st. pauli": "st. pauli",
  "holstein kiel": "kiel",
  // France
  "paris saint-germain": "psg",
  "paris saint-germain fc": "psg",
  "olympique de marseille": "marseille",
  "olympique marseille": "marseille",
  "as monaco": "monaco",
  "as monaco fc": "monaco",
  "olympique lyonnais": "lyon",
  "olympique lyon": "lyon",
  "losc lille": "lille",
  "losc lille métropole": "lille",
  "stade rennais fc": "rennes",
  "stade rennais": "rennes",
  "rc lens": "lens",
  "racing club de lens": "lens",
  "ogc nice": "nice",
  "olympique gymnaste club nice": "nice",
  "rc strasbourg alsace": "strasbourg",
  "rc strasbourg": "strasbourg",
  "fc nantes": "nantes",
  "stade brestois 29": "brest",
  "stade brest": "brest",
  "toulouse fc": "toulouse",
  "montpellier hsc": "montpellier",
  "montpellier hérault sc": "montpellier",
  "le havre ac": "le havre",
  "afc le havre": "le havre",
  "stade de reims": "reims",
  "as saint-étienne": "saint-etienne",
  "as saint-etienne": "saint-etienne",
  "angers sco": "angers",
  "aj auxerre": "auxerre",
  // Portugal
  "fc porto": "porto",
  "sl benfica": "benfica",
  "sporting cp": "sporting",
  "sc braga": "braga",
  "vitória sc": "vitoria sc",
  // Belgium
  "club brugge kv": "club brugge",
  "rsc anderlecht": "anderlecht",
  "kaa gent": "gent",
  "royal antwerp fc": "antwerp",
  "kr genk": "genk",
  "rc genk": "genk",
  // Turkey
  "galatasaray sk": "galatasaray",
  "fenerbahçe sk": "fenerbahce",
  "fenerbahce sk": "fenerbahce",
  "beşiktaş jk": "besiktas",
  "besiktas jk": "besiktas",
  "trabzonspor": "trabzonspor",
  // Scotland
  "celtic fc": "celtic",
  "rangers fc": "rangers",
  "heart of midlothian": "hearts",
  "hibernian fc": "hibernian",
  // Switzerland
  "bsc young boys": "young boys",
  "fc basel 1893": "basel",
  "fc zürich": "zurich",
  "fc zurich": "zurich",
  // Austria
  "fc red bull salzburg": "red bull salzburg",
  "sk rapid wien": "rapid wien",
  "sk sturm graz": "sturm graz",
  // Greece
  "olympiacos fc": "olympiacos",
  "panathinaikos fc": "panathinaikos",
  "paok fc": "paok",
  "aek athens fc": "aek athens",
  // Denmark
  "fc copenhagen": "copenhagen",
  "fc midtjylland": "midtjylland",
  "brøndby if": "brondby",
  "brondby if": "brondby",
  // Sweden
  "malmö ff": "malmo",
  "malmo ff": "malmo",
  "aik stockholm": "aik",
  "djurgårdens if": "djurgardens",
  // Norway
  "molde fk": "molde",
  "rosenborg bk": "rosenborg",
  "bodø/glimt": "bodo glimt",
  "fk bodø/glimt": "bodo glimt",
  // Poland
  "legia warszawa": "legia warsaw",
  "lech poznań": "lech poznan",
  // Czech Republic
  "ac sparta praha": "sparta prague",
  "sk slavia praha": "slavia prague",
  // Croatia
  "gnk dinamo zagreb": "dinamo zagreb",
  "hnk hajduk split": "hajduk split",
  // Ukraine
  "fc shakhtar donetsk": "shakhtar donetsk",
  "fc dynamo kyiv": "dynamo kyiv",
};

// Resolve a team name to its canonical form
export function resolveTeamName(name: string): string {
  const lower = name.toLowerCase().trim();
  return TEAM_NAME_ALIASES[lower] ?? lower;
}
