import { useState } from "react";
import { Header } from "@/components/Header";
import { MatchCard } from "@/components/MatchCard";
import { LeagueFilter } from "@/components/LeagueFilter";
import { useUpcomingMatches, useCompletedMatches } from "@/hooks/useMatches";
import { Skeleton } from "@/components/ui/skeleton";
import { Activity, Clock } from "lucide-react";

const Index = () => {
  const [league, setLeague] = useState("all");
  const { data: upcoming, isLoading: loadingUp } = useUpcomingMatches(league);
  const { data: completed, isLoading: loadingDone } = useCompletedMatches(league);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-6 space-y-8">
        {/* Hero */}
        <div className="space-y-2">
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
            AI Match <span className="text-primary">Predictions</span>
          </h1>
          <p className="text-sm text-muted-foreground">
            Probabilities generated by our prediction engine. Not betting advice.
          </p>
        </div>

        <LeagueFilter selected={league} onChange={setLeague} />

        {/* Upcoming */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Upcoming Matches</h2>
            {upcoming && (
              <span className="text-xs text-muted-foreground">({upcoming.length})</span>
            )}
          </div>
          {loadingUp ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : upcoming?.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {upcoming.map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No upcoming matches found.</p>
          )}
        </section>

        {/* Recent Results */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Recent Results</h2>
          </div>
          {loadingDone ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : completed?.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {completed.slice(0, 6).map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No recent matches.</p>
          )}
        </section>
      </main>
    </div>
  );
};

export default Index;
