import { useState, useEffect, useRef } from "react";
import { Header } from "@/components/Header";
import { MatchCard } from "@/components/MatchCard";
import { LeagueFilter } from "@/components/LeagueFilter";
import { useDashboardMatches, useCompletedMatches } from "@/hooks/useMatches";
import { useSyncFootballData } from "@/hooks/useSync";
import { Skeleton } from "@/components/ui/skeleton";
import { Activity, Clock } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

const HEAL_COOLDOWN_MS = 2 * 60 * 1000; // 2 minutes

const Index = () => {
  const [league, setLeague] = useState("all");
  const queryClient = useQueryClient();
  const lastHealRef = useRef(0);

  const { data: dashboard, isLoading: loadingDash } = useDashboardMatches(league);
  const { data: completed, isLoading: loadingDone } = useCompletedMatches(league);

  const live = dashboard?.live ?? [];
  const upcoming = dashboard?.upcoming ?? [];
  const transitionIds = dashboard?.transitionIds ?? [];

  // Silent auto-heal: when transition_live matches detected, trigger backend sync
  useEffect(() => {
    if (transitionIds.length === 0) return;
    const now = Date.now();
    if (now - lastHealRef.current < HEAL_COOLDOWN_MS) return;
    lastHealRef.current = now;

    supabase.functions.invoke("auto-sync", { body: { mode: "live" } })
      .then(() => {
        // Invalidate after a short delay to let backend process
        setTimeout(() => {
          queryClient.invalidateQueries({ queryKey: ["matches"] });
        }, 3000);
      })
      .catch(() => {/* silent */});
  }, [transitionIds, queryClient]);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-6 space-y-8">
        {/* Hero */}
        <div className="space-y-2">
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
            AI Match <span className="text-primary">Predictions</span>
          </h1>
          <p className="text-sm text-muted-foreground">
            Probabilities generated by our prediction engine. Not betting advice.
          </p>
        </div>

        <LeagueFilter selected={league} onChange={setLeague} />

        {/* Live Matches */}
        {(loadingDash || live.length > 0) && (
          <section className="space-y-4">
            <div className="flex items-center gap-2">
              <span className="relative flex h-3 w-3">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500" />
              </span>
              <h2 className="text-lg font-semibold">Live Matches</h2>
              {!loadingDash && (
                <span className="text-xs text-muted-foreground">({live.length})</span>
              )}
            </div>
            {loadingDash ? (
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {Array.from({ length: 3 }).map((_, i) => (
                  <Skeleton key={i} className="h-56 rounded-lg" />
                ))}
              </div>
            ) : (
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {live.map((m) => (
                  <MatchCard key={m.id} match={m} />
                ))}
              </div>
            )}
          </section>
        )}

        {/* Upcoming */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Upcoming Matches</h2>
            {!loadingDash && upcoming && (
              <span className="text-xs text-muted-foreground">({upcoming.length})</span>
            )}
          </div>
          {loadingDash ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : upcoming.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {upcoming.map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No upcoming matches found.</p>
          )}
        </section>

        {/* Recent Results */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Recent Results</h2>
          </div>
          {loadingDone ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : completed?.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {completed.slice(0, 6).map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No recent matches.</p>
          )}
        </section>
      </main>
    </div>
  );
};

export default Index;
