import { useState, useEffect } from "react";
import { Header } from "@/components/Header";
import { MatchCard } from "@/components/MatchCard";
import { LeagueFilter } from "@/components/LeagueFilter";
import { useUpcomingMatches, useCompletedMatches } from "@/hooks/useMatches";
import { useSyncFootballData } from "@/hooks/useSync";
import { useSyncSportradarData } from "@/hooks/useSportradar";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Activity, Clock, RefreshCw } from "lucide-react";
import { toast } from "sonner";

const SYNC_COOLDOWN_MS = 30 * 60 * 1000; // 30 minutes
const SYNC_KEY = "last_auto_sync";

const Index = () => {
  const [league, setLeague] = useState("all");
  const { data: upcoming, isLoading: loadingUp } = useUpcomingMatches(league);
  const { data: completed, isLoading: loadingDone } = useCompletedMatches(league);
  const sync = useSyncFootballData();
  const srSync = useSyncSportradarData();

  const runSync = () => {
    sync.mutate(undefined, {
      onSuccess: (data) => toast.success(`API-Football synced! ${data?.summary?.matches ?? 0} matches.`),
      onError: (err) => toast.error(`API-Football sync failed: ${err.message}`),
    });
    srSync.mutate(undefined, {
      onSuccess: (data) => {
        const s = data?.summary;
        toast.success(`Sportradar synced! ${s?.matchesCreated ?? 0} new, ${s?.probabilitiesSynced ?? 0} probabilities.`);
      },
      onError: (err) => toast.error(`Sportradar sync failed: ${err.message}`),
    });
  };

  // Auto-sync on load with 30-min cooldown
  useEffect(() => {
    const lastSync = parseInt(localStorage.getItem(SYNC_KEY) || "0", 10);
    const now = Date.now();
    if (now - lastSync > SYNC_COOLDOWN_MS) {
      localStorage.setItem(SYNC_KEY, String(now));
      // Small delay to let the page render first
      const t = setTimeout(() => runSync(), 1000);
      return () => clearTimeout(t);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSync = () => {
    localStorage.setItem(SYNC_KEY, String(Date.now()));
    runSync();
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-6 space-y-8">
        {/* Hero */}
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-2">
            <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
              AI Match <span className="text-primary">Predictions</span>
            </h1>
            <p className="text-sm text-muted-foreground">
              Probabilities generated by our prediction engine. Not betting advice.
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleSync}
            disabled={sync.isPending || srSync.isPending}
            className="shrink-0"
          >
            <RefreshCw className={`h-4 w-4 mr-1 ${(sync.isPending || srSync.isPending) ? "animate-spin" : ""}`} />
            {(sync.isPending || srSync.isPending) ? "Syncing…" : "Sync Live Data"}
          </Button>
        </div>

        <LeagueFilter selected={league} onChange={setLeague} />

        {/* Upcoming */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Upcoming Matches</h2>
            {upcoming && (
              <span className="text-xs text-muted-foreground">({upcoming.length})</span>
            )}
          </div>
          {loadingUp ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : upcoming?.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {upcoming.map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No upcoming matches found.</p>
          )}
        </section>

        {/* Recent Results */}
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Activity className="h-4 w-4 text-primary" />
            <h2 className="text-lg font-semibold">Recent Results</h2>
          </div>
          {loadingDone ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-56 rounded-lg" />
              ))}
            </div>
          ) : completed?.length ? (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {completed.slice(0, 6).map((m) => (
                <MatchCard key={m.id} match={m} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No recent matches.</p>
          )}
        </section>
      </main>
    </div>
  );
};

export default Index;
